import = ["~/.config/alacritty/nord.toml"]

[env]
TERM = "xterm-256color"

[window]
padding.x = 2
padding.y = 2
decorations = "None"
option_as_alt = "OnlyLeft"

[font]
normal.family = "Hurmit Nerd Font"
bold.family = "Hurmit Nerd Font"
size = 8

[scrolling]
history = 100000
multiplier = 10

[mouse]
hide_when_typing = true

[selection]
save_to_clipboard = true

[cursor]
style.shape = "Underline"
style.blinking = "Always"
vi_mode_style.shape = "Underline"
vi_mode_style.blinking = "Always"
blink_interval = 300
blink_timeout = 0

